---
title: "R Notebook"
output: html_notebook
---
```{r}
library(pander)
library(dplyr)
library(tidyr)
library(fluEvidenceSynthesis)
```


```{r}
# Here we load the needed data and regroup it from 5 into two age groups.
library(fluEvidenceSynthesis)
data("demography")
data("polymod_uk")
data("ili")
# Virologically confirmed infections
data("confirmed.samples")

# Group all the example data into two age groups:
polymod <- polymod_uk[,c(1,2)]
polymod[,3] <- rowSums(polymod_uk[,c(3,4,5,6,7,8)])
polymod[,4] <- polymod_uk[,9]

ili_df <- ili
ili_df$ili <- ili$ili[,c(1,2)]
ili_df$ili[,1] <- rowSums(ili$ili[,c(1,2,3,4)])
ili_df$ili[,2] <- ili$ili[,5]
ili_df$total.monitored <- ili$total.monitored[,c(1,2)]
ili_df$total.monitored[,1] <- rowSums(ili$total.monitored[,c(1,2,3,4)])
ili_df$total.monitored[,2] <- ili$total.monitored[,5]

confirmed.samples_df <- confirmed.samples
confirmed.samples_df$positive <- confirmed.samples$positive[,c(1,2)]
confirmed.samples_df$positive[,1] <- rowSums(confirmed.samples$positive[,c(1,2,3,4)])
confirmed.samples_df$positive[,2] <- confirmed.samples$positive[,5]
confirmed.samples_df$total.samples <- confirmed.samples$total.samples[,c(1,2)]
confirmed.samples_df$total.samples[,1] <- rowSums(confirmed.samples$total.samples[,c(1,2,3,4)])
confirmed.samples_df$total.samples[,2] <- confirmed.samples$total.samples[,5]
```

```{r}
data(coverage)
# Coverage rates for the low risk <65 and low risk 65+
cov <- coverage[,c("Under.65","X65")]/100.0

vaccine_calendar <- as_vaccination_calendar(efficacy = c(0.7, 0.4), 
                                        dates = coverage$Date,
                                        coverage = cov, 
                                        no_age_groups = 2, no_risk_groups = 1)
```

```{r}
initial_parameters <- c(0.1, 0.1, 1e-5, 0.16, 0.5, 0.5, -0.15)
names(initial_parameters) <- c("epsilon_1", "epsilon_2", "psi", "transmissibility", "susceptibility_1", "susceptibility_2", "initial_infected")
```

```{r}
inference.res <- inference(demography = demography,
                      vaccine_calendar = vaccine_calendar,
                      polymod_data = as.matrix(polymod),
                      ili = ili_df$ili,
                      mon_pop = ili_df$total.monitored,
                      n_pos = confirmed.samples_df$positive,
                      n_samples = confirmed.samples_df$total.samples,
                      initial = initial_parameters,
                      age_groups = c(65),
                      nbatch = 1000,
                      nburn = 1000, blen = 5 )
```

```{r}
pander(head(inference.res$batch))
```


```{r}
# The custom inference function. In this example the custom inference function 
# performs exactly the same inference as the original C++ function (above). 
# It is up to the user to change this in a way that works for their analysis.
custom_inference <- function(demography, vaccine_calendar, polymod_data, ili, 
                             mon_pop, n_pos, n_samples, initial, mapping,
                             nbatch, nburn, blen) {
  current.contact.ids <- seq(1,nrow(polymod_uk))
  proposed.contact.ids <- current.contact.ids
  
  # Seven age groups used in the model
  age.group.limits <- c(1,5,15,25,45,65)
  
  # Sum all populations with a certain age into their corresponding age group
  age.group.sizes.5 <- stratify_by_age(demography, c(5,15,45,65))
  
  if (missing(mapping))
    mapping <- age_group_mapping(age.group.limits, c(5,15,45,65))
  
  # Define the actual log likelihood function
  llikelihood <- function( pars ) {
    # Resample contact ids 
    proposed.contact.ids <<- current.contact.ids
    if (runif(1,0,1) < 0.1) {
      rs <- round(runif(2,1,length(proposed.contact.ids)))
      proposed.contact.ids[rs[1]] <<- rs[2]
    }
    
    contacts <- contact_matrix(as.matrix(polymod_uk[proposed.contact.ids,]),
                               demography, age.group.limits )
    
    age.groups <- stratify_by_age(demography, 
                                  age.group.limits )
    
    # Fraction of each age group classified as high risk
    # We can classify a third risk group, but we are not doing
    # that here (the second row is 0 in our risk.ratios matrix)
    risk.ratios <- matrix(c(
      0.021, 0.055, 0.098, 0.087, 0.092, 0.183, 0.45, 
      0, 0, 0, 0, 0, 0, 0                          
    ), ncol = 7, byrow = T)
    
    # Population sizes in each age and risk group
    popv <- stratify_by_risk(
      age.groups, risk.ratios );
    
    # Population size initially infected by age and risk group
    initial.infected <- rep( 10^pars[9], 7 ) # 7 for number of age groups (in the ILI data, not virological)
    initial.infected <- stratify_by_risk(
      initial.infected, risk.ratios );
    
    # Run simulation
    # Note that to reduce complexity 
    # we are using the same susceptibility parameter for multiple age groups
    odes <- infectionODEs( popv, initial.infected,
                           vaccine_calendar,
                           contacts,
                           c(pars[6], pars[6], pars[6],
                             pars[7], pars[7], pars[7], pars[8]),
                           transmissibility = pars[5],
                           c(0.8,1.8), 7 )
    
    # Ignore times row
    odes <- odes[,2:22]
    
    # Convert the 7 age groups for each risk group to 5 groups
    from <- as.numeric(mapping$from)
    to <- as.numeric(mapping$to)
    converted.odes <- matrix(0, nrow = nrow(odes), ncol = max(to))
    for (i in 1:nrow(mapping)) {
      # all three age groups
      fv <- c(0,7,14) + from[i]
      converted.odes[,to[i]] <- converted.odes[,to[i]] + mapping$weight[i]*rowSums(odes[,fv]) 
    }
    
    # For each week and each group sum log likelihood
    epsilons <- c(pars[1], pars[1], pars[2], pars[2], pars[3])
    ll <- log_likelihood_cases(
      epsilons,pars[4], as.matrix(converted.odes),
      age.group.sizes.5, ili, mon_pop,
      n_pos, n_samples)
    return(ll)
  }
  llprior <- function(pars) {
    if (any(pars[1:8] < 0) || any(pars[1:4] > 1) || any(pars[6:8] > 1)
        || pars[9] < log(0.00001) || pars[9] > log(10) )
      return(-Inf)
    
    lprob <- dnorm(pars[5], 0.1653183, 0.02773053, 1)
    lprob <- lprob + dlnorm(pars[1], -4.493789, 0.2860455, 1)
    lprob <- lprob + dlnorm(pars[2], -4.117028, 0.4751615, 1)
    lprob <- lprob + dlnorm(pars[3], -2.977965, 1.331832, 1)
    
    return(lprob)
  }
  
  # Store the contact ids used during inference
  contact.ids <- list()
  
  # Run adaptive.mcmc
  mcmc.result <- adaptive.mcmc(lprior = llprior, llikelihood = llikelihood, 
                               outfun = function() { 
                                 contact.ids[[length(contact.ids)+1]] <<-  current.contact.ids
                               },
                               acceptfun = function() {
                                 current.contact.ids <<- proposed.contact.ids
                               },
                               nburn = nburn, 
                               initial = initial,
                               nbatch = nbatch, blen = blen)
  mcmc.result$contact.ids <- t(data.frame(contact.ids))
  mcmc.result
}


# The resulting custom inference function can be called similarly to the original inference function.

initial.parameters <- c(0.01188150, 0.01831852, 0.05434378,
                        1.049317e-05, 0.1657944,
                        0.3855279, 0.9269811, 0.5710709,
                        -0.1543508)
# Adding names for clarity, is not actually needed
names(initial.parameters) <- c("espilon_1", "epsilon_2", "epsilon_3", "psi",
                               "transmissibility", "susceptibility_1", "susceptibility_2", "suceptibility_3",
                               "initial_infected")


inference.res <- custom_inference(demography = demography,
                      vaccine_calendar = vaccine_calendar,
                      polymod_data = as.matrix(polymod_uk),
                      ili = ili$ili,
                      mon_pop = ili$total.monitored,
                      n_pos = confirmed.samples$positive,
                      n_samples = confirmed.samples$total.samples,
                      initial = initial.parameters,
                      nbatch = 1000,
                      nburn = 1000, blen = 5 )

```

# Analysing the results

Plotting the resulting posterior parameter values^[Be aware that these results are for a very short mcmc run and are not realistic].

```{r,cache=T,fig.width=5,fig.height=5}
library(reshape2)
library(ggplot2)
colnames(inference.results$batch) <- c("eps1", "eps2", "eps3", "psi", "q",
                                       "susc1", "susc2", "susc3", "I0")

ggplot(data=melt(inference.results$batch)) + facet_wrap( ~ Var2, ncol=3, scales="free" ) + geom_histogram(aes(x=value), bins=25)

```

## Posterior model results

Here we plot the credibility intervals of our models. Each plot is the result for one of the seven age groups and shows the number of new cases each week.

```{r,cache=T, fig.width=5, fig.height=5}
library(fluEvidenceSynthesis)
library(ggplot2)

# Function that runs the model given a set of parameters. Most of the function
# has todo with loading the correct inputs for the ODE model
ode.results <- function( pars ) 
{
  data("demography")
  
  age.group.limits <- c(1,5,15,25,45,65)
  contacts <- contact_matrix(as.matrix(polymod_uk),
                             demography, age.group.limits )
  
  age.groups <- stratify_by_age(demography, age.group.limits)
  
  # Fraction of each age group classified as high risk
  # We can classify a third risk group, but we are not doing
  # that here (the second row is 0 in our risk.ratios matrix)
  risk.ratios <- matrix( c(
    0.021, 0.055, 0.098, 0.087, 0.092, 0.183, 0.45, 
    0, 0, 0, 0, 0, 0, 0                          
  ), ncol=7, byrow=T )
  
  # Population sizes in each age and risk group
  popv <- stratify_by_risk(
    age.groups, risk.ratios )
  
  # Population size initially infected by age and risk group
  initial.infected <- rep( 10^pars[9], 7 )
  initial.infected <- stratify_by_risk(
    initial.infected, risk.ratios )
  
  
  # Run simulation
  # Note that to reduce complexity 
  # by using the same susceptibility parameter for multiple age groups
  odes <- infectionODEs( popv, initial.infected,
                         vaccine_calendar,
                         contacts,
                         c(pars[6],pars[6],pars[6],
                           pars[7],pars[7],pars[7],pars[8]),
                         transmissibility=pars[5],
                         c(0.8,1.8), 7 )
  
  # For simplicity we sum the low and high risk group
  simplify.odes <- odes[,2:8]+odes[,9:15]+odes[,16:22]
  rownames(simplify.odes) <- odes[,1]
  return( simplify.odes)
}

# Calculate the credibility intervals for each time point. By default the function
# calculate it for the (equal tailed) credibility interval of 0% (median), 50% and 98%
cim <- credible.interval.model(ode.results, inference.res$batch, intervals=c(0,0.5, 0.98))
cim$row.ID <- as.Date(as.character(cim$row.ID)) 

ggplot( data=cim ) + facet_wrap( ~ column.ID, ncol=3, scales="free" ) +
  stat_ci( aes(row.ID,value, ci = aggregate) ) +
  xlab("Time") + ylab("New infections")
```


```{r}

```



