```{r,include=F}
library(fluEvidenceSynthesis)
library(pander)
library(ggplot2)
library(dplyr)
library(tidyr)
library(epiparameter)

data(polymod_uk)
data(demography)
```

# Implement the vignette modelling runs in an easy function

```{r}
run_model_vignette <- function(population, initial.infected, vaccine_calendar, contacts, 
               susceptibility, transmissibility, infection_delays, interval) {
    
    # Run model and store results
    odes <- infectionODEs( population, initial.infected, vaccine_calendar, contacts, 
               susceptibility, transmissibility, infection_delays, interval)
    
    # Compute fraction of each subpopulation that is infective at any point in time
    fraction.infected <- odes %>%
    gather(Group, Incidence, -Time) %>%
    mutate(fraction = Incidence/population[Group])
    
    return(fraction.infected)
}
```

```{r}
####################################################################################
# POPULATION DATA
####################################################################################

# Separate into non elderly (<65) and elderly population
ag <- stratify_by_age(demography, limits=c(65)) # c( 43670500, 8262600 )

# Separate in risk groups. In this case we assume one additional (high) risk groups and that respectively 
# 1 percent of non elderly and 40% of elderly are in this risk group. It is possible to
# define an additional risk group (e.g. pregnant women) if desired
population <- stratify_by_risk(ag, matrix(c(0.01,0.4),nrow=1), 
                                labels = c("LowRisk", "HighRisk")) # c( 43233795, 4957560, 436705, 3305040 )
```

```{r}
####################################################################################
# INTEGRATION dt
####################################################################################

interval <- 7
```


```{r}
####################################################################################
# INITIAL INFECTED
####################################################################################

ag <- c(1000,1000)
initial.infected <- stratify_by_risk( ag, matrix(c(0.01,0.4),nrow=1)) # c(990, 600, 10, 400)
```

```{r}
####################################################################################
# VACCINE CALENDAR
####################################################################################

vaccine_calendar <- as_vaccination_calendar(
  efficacy = c(0.7,0.4),
  coverage = as.data.frame(matrix(c(0,0,0,0,0,0.861,0.123,0.861, 0,0.861,0.123,0.861, 0,0.861,0.123,0.861, 0,0.861,0.123,0.861, 0,0.861,0.123,0.861), nrow = 6, byrow = T)),
  dates = c(as.Date("2023-10-01"), as.Date("2023-11-01"), as.Date("2023-12-01"), as.Date("2024-01-01"), as.Date("2014-02-01"), as.Date("2024-03-01")), # begin and end date
  no_age_groups = 2,
  no_risk_groups = 2
)
```

```{r}
####################################################################################
# CONTACT RATES BETWEEN AGE GROUPS
####################################################################################

# Polymod data is subdivided in seven age groups
poly <- polymod_uk[,c(1,2,3,9)]
poly[,3] <- rowSums(polymod_uk[,3:8])

contacts <- contact_matrix(as.matrix(poly), demography, c(65))
pander(contacts)
```
```{r}
####################################################################################
# EPIDEMIOLOGICAL PARAMETERS
####################################################################################

susceptibility <- c(0.7, 0.3) # Different for different ages
transmissibility <- 0.14 # Same for all ages
infection_delays <- c( 0.8, 2.5 ) # 0.8 and 1.8 day.
```

```{r}
####################################################################################
# ITERATE OVER TRANSMISSIBILITY VALUES
####################################################################################

# Define a range of transmissibility values to iterate over
transmissibility_values <- seq(0.10, 0.18, by = 0.02)


# Now loop over the remaining transmissibility values starting from the second one
for(t in transmissibility_values) {  # Exclude the first element since it's already processed
  model_data <- run_model_vignette(population, initial.infected, vaccine_calendar, contacts,
                   susceptibility, t, infection_delays, interval)
  plot <- ggplot(model_data) + geom_line( aes(x=Time, y=fraction, colour = Group) ) + 
  ylab( "Fraction infected") + ggtitle(paste('Transmissibility = ', t))
  print(plot)
}

# Plot all curves on the same figure
#plot_object <- ggplot(data = all_data, aes(x = Time, y = fraction, colour = Group, linetype = factor(Transmissibility))) + geom_line() + ylab("Fraction infected")

#print(plot_object)

# Save the plot to a PDF file
#ggsave("output.pdf", plot = plot_object, width = 7, height = 5)


```